### ISSUE TITLE
Java 14 compatibility

### ISSUE THREAD

**Issue by SlimeDog** [OtakuMegane/TallNether#6]
CentOS Linux 7.8.2003
Java 14.0.2
Spigot 1.16.3
TallNether 2.5.1

On server start-up:
```
[17:11:59] [Server thread/WARN]: java.lang.NoSuchFieldException: modifiers
[17:11:59] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2489)
[17:11:59] [Server thread/WARN]:        at com.minefit.xerxestireiron.tallnether.v1_16_R2.ReflectionHelper.setFinal(ReflectionHelper.java:31)
[17:11:59] [Server thread/WARN]:        at com.minefit.xerxestireiron.tallnether.v1_16_R2.LoadHell.setGenerator(LoadHell.java:133)
[17:11:59] [Server thread/WARN]:        at com.minefit.xerxestireiron.tallnether.v1_16_R2.LoadHell.overrideGenerator(LoadHell.java:103)
[17:11:59] [Server thread/WARN]:        at com.minefit.xerxestireiron.tallnether.ManageHell.overrideGenerator(ManageHell.java:109)
[17:11:59] [Server thread/WARN]:        at com.minefit.xerxestireiron.tallnether.TallNether.prepareWorld(TallNether.java:95)
[17:11:59] [Server thread/WARN]:        at com.minefit.xerxestireiron.tallnether.TallNether.onWorldInit(TallNether.java:64)
[17:11:59] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:11:59] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:11:59] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:11:59] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[17:11:59] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
[17:11:59] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:11:59] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[17:11:59] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[17:11:59] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.createWorld(CraftServer.java:1066)
[17:11:59] [Server thread/WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:524)
[17:11:59] [Server thread/WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325)
[17:11:59] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[17:11:59] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448)
[17:11:59] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423)
[17:11:59] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728)
[17:11:59] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310)
[17:11:59] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:11:59] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[17:11:59] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[17:11:59] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[17:11:59] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[17:11:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[17:11:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216)
[17:11:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[17:11:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[17:11:59] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[17:11:59] [Server thread/INFO]: [TallNether Error] Something went wrong enabling TallNether on world 'world_whitedog_nether'.
```
No issues on Java 8 or 11.

**Comment by OtakuMegane** [comment]
Looks like the changes they made in Java 14 to block the reflection classes from modifying final fields. I'll have to get another method worked out for 14+.

**Comment by SlimeDog** [comment]
Yep. :)
Something about "security". :(
No hurry. It's a test server. The other one is Java 11 -- works fine.

**Comment by andrewkm** [comment]
Same here, works fine in Java 11.
Java 14 is rip.

**Comment by OtakuMegane** [comment]
Think I've found a solution but want to verify on some other systems as well before committing it. Posting an experimental build here: https://www.dropbox.com/s/kkyay0o64ifhip2/TallNether-java14-experimental-1.jar?dl=0

If it works for everyone I'll get it into the next update.

**Comment by SlimeDog** [comment]
Java14-experimental-1 seems fine on both Java 11.0.9 and Java 14.0.2
